[package]
name = "velin-bytecode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Validated bytecode model and execution plans for Velin"

[features]
default = ["serde"]
serde = ["dep:serde", "velin-syntax/serde"]

[dependencies]
velin-syntax = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive", "rc"], optional = true }

[lints]
workspace = true
